# Generated by Django 3.2 on 2022-02-04 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='count_nn',
            field=models.IntegerField(default=0),
        ),
    ]
